//--------------------------------------------------------------------------------
// Auto-generated by LiteX (e5fa4cbaf) on 2025-11-05 20:57:53
//--------------------------------------------------------------------------------
#ifndef __GENERATED_GIT_H
#define __GENERATED_GIT_H

#define LITEX_GIT_SHA1 "e5fa4cbaf"
#endif
