//--------------------------------------------------------------------------------
// Auto-generated by LiteX (e5fa4cbaf) on 2025-11-05 20:57:53
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef MAIN_RAM_BASE
#define MAIN_RAM_BASE 0x00000000L
#define MAIN_RAM_SIZE 0x00001000
#endif

#ifndef CSR_BASE
#define CSR_BASE 0xc8000000L
#define CSR_SIZE 0x00010000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "MAIN_RAM  0x00000000 0x1000 \nCSR       0xc8000000 0x10000 "
#endif
#endif
