//--------------------------------------------------------------------------------
// Auto-generated by LiteX (e5fa4cbaf) on 2025-11-05 20:57:53
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#define CONFIG_PLATFORM_NAME "microwatt_3"
#define CONFIG_CLOCK_FREQUENCY 50000000
#define CONFIG_CPU_RESET_ADDR 0
#define CONFIG_CPU_TYPE_MICROWATT
#define CONFIG_CPU_VARIANT_STANDARD
#define CONFIG_CPU_FAMILY "ppc64"
#define CONFIG_CPU_NAME "microwatt"
#define CONFIG_CPU_HUMAN_NAME "Microwatt"
#define CONFIG_CPU_NOP "nop"
#define CONFIG_BIOS_NO_BUILD_TIME
#define CONFIG_IDENTIFIER "Microwatt CF-SRAM SoC with UART for Caravel"
#define UART_POLLING
#define CONFIG_CSR_DATA_WIDTH 32
#define CONFIG_CSR_ALIGNMENT 32
#define CONFIG_CSR_ORDERING_BIG
#define CONFIG_BUS_STANDARD "wishbone"
#define CONFIG_BUS_DATA_WIDTH 32
#define CONFIG_BUS_ADDRESS_WIDTH 32
#define CONFIG_BUS_BURSTING 0

#ifndef __ASSEMBLER__
static inline const char * config_platform_name_read(void) {
	return "microwatt_3";
}
static inline int config_clock_frequency_read(void) {
	return 50000000;
}
static inline int config_cpu_reset_addr_read(void) {
	return 0;
}
static inline const char * config_cpu_family_read(void) {
	return "ppc64";
}
static inline const char * config_cpu_name_read(void) {
	return "microwatt";
}
static inline const char * config_cpu_human_name_read(void) {
	return "Microwatt";
}
static inline const char * config_cpu_nop_read(void) {
	return "nop";
}
static inline const char * config_identifier_read(void) {
	return "Microwatt CF-SRAM SoC with UART for Caravel";
}
static inline int config_csr_data_width_read(void) {
	return 32;
}
static inline int config_csr_alignment_read(void) {
	return 32;
}
static inline const char * config_bus_standard_read(void) {
	return "wishbone";
}
static inline int config_bus_data_width_read(void) {
	return 32;
}
static inline int config_bus_address_width_read(void) {
	return 32;
}
static inline int config_bus_bursting_read(void) {
	return 0;
}
#endif // !__ASSEMBLER__

#endif
